zeus:
  name: commons datasource configs for develop
  version: 1.0

#kafka配置
kafka:
  host: localhost
  port: 9092

#mongodb配置
spring:
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017

#仅输出ERROR日志
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: ERROR
